services:
  app:
    build: .
    container_name: obtener-materia
    ports:
      - "2001:9090"
    volumes:
      - ./estudiantes.db:/app/estudiantes.db
    env_file:
      - .env
    restart: unless-stopped
